version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
  python_server:
    build: ./python_server
    container_name: python_server
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto

volumes:
  mosquitto_data:
  mosquitto_logs:
